project:
  namespace: "org.simplemodeling"
  id: "SimpleModelingModel"
  kind: "library"
  component:
    version: "0.2.2-SNAPSHOT"

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.3-SNAPSHOT"

packaging:
  kind: "maven"
